#!/usr/bin/env python3

import os
import getopt
import sys
import operator
import time
import stat
import pwd
import grp

'''
License: https://opensource.org/licenses/MIT
Author: Scott Fehrman sfehrman@me.com

THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE.
'''

VERSION = "1.0.1"
GETOPT_STR = "bcd:hilmn:ps:t:u:vABCDLRST"
_accessed = "accessed"
_blocks = "blocks"
_error = "error"
_inode = "inode"
_group = "group"
_link = "link"
_message = "message"
_mode = "mode"
_modified = "modified"
_name = "name"
_size = "size"
_stat = "stat"
_status = "status"
_symbolic = "symbolic"
_user = "user"
pad_chars = 3
max_name_len = 1
display_columns = 0
entries_list = []
files_list = []
dirs_list = []
args_list = []
names_list = []
sort_by = _name
show_files = True
show_dirs = True
use_count_only = False  # do not show the files / dirs, just the count data
use_brief = False  # do not print extra blank lines
use_single_col = False  # show files / directories in a single column
use_detail = False
use_reverse = False
show_dot = True  # show hidden files (name begins with a dot)
show_hdr = True  # show column headers with alternate output format
show_name = True  # show the user and group names instead of uid and gid
show_pwd = True  # show the directory path
show_qty = True  # show the quantities for Entries, Files, Directories
show_link = False  # show symbolic link info, not what link points to
show_mode = False  # Show the permission mode [4777]
display_col_size = False
display_col_dtm = False  # show Date Time modified
display_col_dta = False  # show Date Time accessed
display_col_dts = False  # show Date Time status changed (chmod)
display_col_inode = False  # show Inode number
display_col_link = False  # show link count
display_col_blocks = False  # show blocks allocated
display_col_type = False  # show the file type
display_col_perm = False  # show the file permissions (rwx...)
need_mode = False
date_format_YMD = '%Y-%m-%d %H:%M:%S'
date_format_MDY = '%m-%d-%Y %H:%M:%S'
date_format_DMY = '%d-%m-%Y %H:%M:%S'
date_format = date_format_YMD
unit_divide = 1  # byte = 1, KB = 1000 ** 1, MB = 1000 ** 2, GB = 1000 ** 3
unit_text = ""


# --------
# functions
# --------


def show_help():
    text = """
    -b        brief, unformatted output
    -c        count entries only
    -d <args> date/time options: [all|dtm|dta|dts] [mdy|dmy|ymd]
    -h        help
    -i        show inode numbers
    -l        show symbolic link's status
    -m        show permissions mode [4777]
    -n <args> no output options: [dot,hdr,name,pwd,qty]
    -p        permissions: rwx rwx rwx   name.group
    -s <args> sorting options: [none|name|dtm|dta|dts|inode|link|size,rev] (default = '-s name') 
    -t <args> select type: [file|f,dir|d] (default show both) 
    -u <args> select unit for file size: [b|k|m|g] (default = '-u b') implicitly uses '-S'
    -v        program version
    -A        show all entries (including '.' and '..')
    -B        show file blocks allocated
    -C        output using single column
    -D        show sub-directory information not it's entries (treat it like a file)
    -L        show hard link count
    -R        recursive list into sub-directories
    -S        show file size (default = bytes)
    -T        show file types
    """
    print(text)
    exit(0)


def get_entry(entry_name, path_name):
    entry_data = {}
    is_error = False
    is_link = False
    link_info = ""
    err_msg = ""

    """
    Dictionary for an Entry:
    {
      "name": "foo",
      "symbolic": "../../real/file" | "(Broken Link)" | "(Link Info)",
      "link": True,
      "size": 1234,
      "modified": "date/time",
      "accessed": "date/time",
      "status": "date/time"
    }
    """

    entry_data.update({_name: entry_name})

    try:
        if os.path.exists(path_name):
            if os.path.islink(path_name):
                is_link = True
                if show_link:
                    entry_stat = os.lstat(path_name)
                    link_info = "(Link Data)"
                else:
                    entry_stat = os.stat(path_name)
                    link_info = os.readlink(path_name)
            else:
                entry_stat = os.stat(path_name)
        else:  # might be a broken symbolic link try "lstat()"
            entry_stat = os.lstat(path_name)
            is_link = True
            link_info = "(Bad Link) " + os.readlink(path_name)
    except OSError as e:
        is_error = True
        err_msg = str(e)

    if is_error:
        entry_data.update({_error: True})

        entry_data.update({_message: err_msg})
    else:
        entry_data.update({_error: False})

        if is_link:
            entry_data.update({_symbolic: link_info})

        if need_mode:
            entry_data.update({_mode: entry_stat.st_mode})

        if display_col_size:
            entry_data.update({_size: entry_stat.st_size})
        if display_col_blocks:
            entry_data.update({_blocks: entry_stat.st_blocks})
        if display_col_dtm:
            entry_data.update({_modified: entry_stat.st_mtime})
        if display_col_dta:
            entry_data.update({_accessed: entry_stat.st_atime})
        if display_col_dts:
            entry_data.update({_status: entry_stat.st_ctime})
        if display_col_inode:
            entry_data.update({_inode: entry_stat.st_ino})
        if display_col_link:
            entry_data.update({_link: entry_stat.st_nlink})
        if display_col_perm:
            entry_data.update({_user: entry_stat.st_uid, _group: entry_stat.st_gid})

    # print("entry_data: " + str(entry_data))  # debug

    return entry_data


def sort_entries(random_list):
    if len(sort_by) == 0:
        return random_list
    else:
        return sorted(random_list, key=operator.itemgetter(sort_by), reverse=use_reverse)


def display_default(data_list):
    count = 0
    fill = 0
    newline = False

    if not use_brief:
        print("")

    if use_single_col:
        for data in data_list:
            print(data[_name])
    else:
        count = 0
        for data in data_list:
            count += 1

            print(data[_name], end='')

            if count < display_columns:
                fill = (max_name_len - len(data[_name]))
                print(' ' * fill, end='')
                newline = True
            else:
                count = 0
                print("")
                newline = False

        if newline:
            print("")
    return


def display_details(data_list):
    pwd_data = {}
    grp_data = {}
    user_name = ""
    group_name = ""

    if not use_brief:
        print("")

        print("Name" + ' ' * (max_name_len - 4), end='')

        if display_col_size:
            print(' ' * (16 - len(unit_text)) + unit_text, end='')

        if display_col_blocks:
            print(' ' * 6 + 'Blocks', end='')

        if display_col_inode:
            print(' ' * 7 + 'Inode', end='')

        if display_col_link:
            print(' ' * 3 + 'Links', end='')

        if display_col_perm:
            if show_mode:
                print(' ' * pad_chars + 'User  Group Other   [Mode]        User.Group' + ' ' * 7, end='')
            else:
                print(' ' * pad_chars + 'User  Group Other           User.Group' + ' ' * 7, end='')

        if display_col_dtm:
            print(' ' * pad_chars + 'Modified' + ' ' * 11, end='')

        if display_col_dta:
            print(' ' * pad_chars + 'Accessed' + ' ' * 11, end='')

        if display_col_dts:
            print(' ' * pad_chars + 'Status Changed' + ' ' * 5, end='')

        if display_col_type:
            print(' ' * pad_chars + 'Type' + ' ' * 12, end='')

        print("")

        print("-" * terminalCols)

    for data in data_list:
        print(data[_name], end='')

        fill = (max_name_len - len(data[_name]))
        print(' ' * fill, end='')

        if data[_error]:
            print(' ' * pad_chars + data[_message])
        else:
            if display_col_size:
                size = data[_size] // unit_divide
                print(' ' * (16 - len(str(size))) + str(size), end='')

            if display_col_blocks:
                print(' ' * (12 - len(str(data[_blocks]))) + str(data[_blocks]), end='')

            if display_col_inode:
                print(' ' * (12 - len(str(data[_inode]))) + str(data[_inode]), end='')

            if display_col_link:
                print(' ' * (8 - len(str(data[_link]))) + str(data[_link]), end='')

            if display_col_perm:
                # ---- User

                print(' ' * pad_chars, end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IRUSR == stat.S_IRUSR:
                    print('r', end='')
                else:
                    print('-', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IWUSR == stat.S_IWUSR:
                    print('w', end='')
                else:
                    print('-', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IXUSR == stat.S_IXUSR:
                    if stat.S_IMODE(data[_mode]) & stat.S_ISUID == stat.S_ISUID:
                        print('s', end='')
                    else:
                        print('x', end='')
                else:
                    if stat.S_IMODE(data[_mode]) & stat.S_ISUID == stat.S_ISUID:
                        print('S', end='')
                    else:
                        print('-', end='')

                # ---- Group

                print('   ', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IRGRP == stat.S_IRGRP:
                    print('r', end='')
                else:
                    print('-', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IWGRP == stat.S_IWGRP:
                    print('w', end='')
                else:
                    print('-', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IXGRP == stat.S_IXGRP:
                    if stat.S_IMODE(data[_mode]) & stat.S_ISGID == stat.S_ISGID:
                        print('s', end='')
                    else:
                        print('x', end='')
                else:
                    if stat.S_IMODE(data[_mode]) & stat.S_ISGID == stat.S_ISGID:
                        print('S', end='')
                    else:
                        print('-', end='')

                # ---- Other

                print('   ', end='')

                if stat.S_IMODE(data[_mode]) & stat.S_IROTH == stat.S_IROTH:
                    print('r', end='')
                else:
                    print('-', end='')
                if stat.S_IMODE(data[_mode]) & stat.S_IWOTH == stat.S_IWOTH:
                    print('w', end='')
                else:
                    print('-', end='')
                if stat.S_IMODE(data[_mode]) & stat.S_IXOTH == stat.S_IXOTH:
                    print('x', end='')
                else:
                    print('-', end='')

                print('     ', end='')

                if show_mode:
                    print('[' + oct(data[_mode])[-4:] + ']', end='')

                if show_name:
                    pwd_data = pwd.getpwuid(data[_user])
                    grp_data = grp.getgrgid(data[_group])

                    user_name = pwd_data[0]
                    group_name = grp_data[0]

                    if len(user_name) > 12:
                        user_name = user_name[:12]

                    if len(group_name) > 12:
                        group_name = group_name[:12]

                    print(' ' * (12 - len(user_name)) + user_name + '.', end='')
                    print(str(group_name) + ' ' * (12 - len(str(group_name))), end='')
                else:
                    print(' ' * (12 - len(str(data[_user]))) + str(data[_user]) + '.', end='')
                    print(str(data[_group]) + ' ' * (12 - len(str(data[_group]))), end='')

            if display_col_dtm:
                print(' ' * pad_chars + str(time.strftime(date_format, time.localtime(data[_modified]))), end='')

            if display_col_dta:
                print(' ' * pad_chars + str(time.strftime(date_format, time.localtime(data[_accessed]))), end='')

            if display_col_dts:
                print(' ' * pad_chars + str(time.strftime(date_format, time.localtime(data[_status]))), end='')

            if display_col_type:
                print(' ' * pad_chars, end='')
                if stat.S_ISLNK(data[_mode]):
                    print('Symbolic Link   ', end='')
                elif stat.S_ISCHR(data[_mode]):
                    print('Character Device', end='')
                elif stat.S_ISBLK(data[_mode]):
                    print('Block Device    ', end='')
                elif stat.S_ISFIFO(data[_mode]):
                    print('FIFO            ', end='')
                elif stat.S_ISREG(data[_mode]):
                    print('Regular File    ', end='')
                elif stat.S_ISSOCK(data[_mode]):
                    print('Socket          ', end='')
                elif stat.S_ISDOOR(data[_mode]):
                    print('Door            ', end='')
                if stat.S_ISDIR(data[_mode]):
                    print('Directory       ', end='')

            if _symbolic in data:
                print(' -> ' + data[_symbolic], end='')

        print('')

    return


# --------
# processing
# --------


inputList = sys.argv[1:]
terminalCols = os.get_terminal_size(0).columns  # size(x) = 0,1,2,3

try:
    args_list, names_list = getopt.getopt(inputList, GETOPT_STR)
except getopt.error as e:
    print(str(e))
    exit(1)

# print(argsList)
# print(namesList)
# exit(0)

for flag, option in args_list:
    # print("flag: '" + flag + "', option: '" + option + "'")
    if flag == "-b":
        use_brief = True
    elif flag == "-c":
        use_count_only = True
    elif flag == "-d":
        for subopt in option.split(","):
            if subopt == "dtm":
                display_col_dtm = True
                use_detail = True
            elif subopt == "dta":
                display_col_dta = True
                use_detail = True
            elif subopt == "dts":
                display_col_dts = True
                use_detail = True
            elif subopt == "all":
                display_col_dtm = True
                display_col_dta = True
                display_col_dts = True
                use_detail = True
            elif subopt == "mdy":
                date_format = date_format_MDY
            elif subopt == "dmy":
                date_format = date_format_DMY
            elif subopt == "ymd":
                date_format = date_format_YMD
            else:
                print("Invalid value '" + subopt + "' for switch '-d'")
                exit(1)
    elif flag == "-h":
        show_help()
    elif flag == "-i":
        display_col_inode = True
        use_detail = True
    elif flag == "-l":
        show_link = True
    elif flag == "-m":
        need_mode = True
        show_mode = True
        display_col_perm = True
        use_detail = True
    elif flag == "-n":
        for subopt in option.split(","):
            if subopt.lower() == "dot":
                show_dot = False
            elif subopt.lower() == "hdr":
                show_hdr = False
            elif subopt.lower() == "name":
                show_name = False
            elif subopt.lower() == "pwd":
                show_pwd = False
            elif subopt.lower() == "qty":
                show_qty = False
            else:
                print("Unknown sub option '" + subopt + "' for switch '-n'")
                exit(1)
    elif flag == "-p":
        need_mode = True
        display_col_perm = True
        use_detail = True
    elif flag == "-s":
        for subopt in option.split(","):
            if subopt.lower() == "none":
                sort_by = ""
            elif subopt.lower() == "rev":
                use_reverse = True
            elif subopt.lower() == "size":
                sort_by = _size
                display_col_size = True
                use_detail = True
            elif subopt.lower() == "dtm":
                sort_by = _modified
                display_col_dtm = True
                use_detail = True
            elif subopt.lower() == "dta":
                sort_by = _accessed
                display_col_dta = True
                use_detail = True
            elif subopt.lower() == "dts":
                sort_by = _status
                display_col_dts = True
                use_detail = True
            elif subopt.lower() == "inode":
                sort_by = _inode
                display_col_inode = True
                use_detail = True
            elif subopt.lower() == "link":
                sort_by = _link
                display_col_link = True
                use_detail = True
            else:
                print("Unknown sub option '" + subopt + "' for switch '-s'")
                exit(1)
    elif flag == "-t":
        if option.lower().startswith("f"):
            show_files = True
            show_dirs = False
        elif option.lower().startswith("d"):
            show_files = False
            show_dirs = True
        else:
            print("Invalid value '" + option + "' for switch '-t'")
            exit(1)
    elif flag == "-u":
        use_detail = True
        display_col_size = True
        for subopt in option.split(","):
            if subopt.lower() == "b":
                unit_divide = 1
                unit_text = "Size (Bytes)"
            elif subopt.lower() == "k":
                unit_divide = 1000 ** 1
                unit_text = "Size (KBytes)"
            elif subopt.lower() == "m":
                unit_divide = 1000 ** 2
                unit_text = "Size (MBytes)"
            elif subopt.lower() == "g":
                unit_divide = 1000 ** 3
                unit_text = "Size (GBytes)"
            else:
                print("Unkown sub option '" + subopt + "' for switch '-u'")
                exit(1)
    elif flag == "-v":
        print('Print Directory (pd) v' + VERSION + ' Python Edition')
        exit(0)
    elif flag == "-B":
        display_col_blocks = True
        use_detail = True
    elif flag == "-C":
        use_single_col = True
    elif flag == "-L":
        display_col_link = True
        use_detail = True
    elif flag == "-S":
        unit_divide = 1
        unit_text = "Size (Bytes)"
        display_col_size = True
        use_detail = True
    elif flag == "-T":
        need_mode = True
        display_col_type = True
        use_detail = True

if len(names_list) == 0:
    names_list.append(".")

for name in names_list:
    entries_list = []
    files_list = []
    dirs_list = []
    sortedList = []
    max_name_len = 1

    if not use_brief:
        print("")
        if len(names_list) > 1:
            print("-" * terminalCols)

    if name == ".":
        name = os.getcwd()

    if not os.path.exists(name):
        print("No such file or directory: '" + name + "\n")
        exit(2)

    if os.path.isdir(name):
        try:
            entries_list = os.listdir(name)
        except FileNotFoundError as e:
            print("File Not Found: '" + name + "'")
            continue
        except PermissionError as e:
            print("Permission Denied: '" + name + "'")
            continue
    else:
        entries_list.append(name)

    for entry in entries_list:
        if entry.startswith(".") and not show_dot:
            continue

        pathname = os.path.join(name, entry)

        if os.path.isdir(pathname):
            dirs_list.append(get_entry(entry, pathname))
        else:
            files_list.append(get_entry(entry, pathname))

        if (len(entry) + pad_chars) > max_name_len:
            max_name_len = len(entry) + pad_chars

    if show_pwd:
        print(name, end="")
    if show_qty:
        if show_pwd:
            print("   ", end="")
        print("Entries: " + str(len(entries_list)), end="")
    if show_pwd or show_qty:
        print("")

    display_columns = terminalCols // max_name_len

    if show_files and len(files_list) > 0:
        if not use_brief:
            print("")

        if show_qty:
            print("Files: " + str(len(files_list)))

        if len(files_list) > 0 and not use_count_only:
            sortedList = sort_entries(files_list)

            if use_detail:
                display_details(sortedList)
            else:
                display_default(sortedList)

    if show_dirs and len(dirs_list) > 0:
        if not use_brief:
            print("")

        if show_qty:
            print("Directories: " + str(len(dirs_list)))

        if len(dirs_list) > 0 and not use_count_only:
            sortedList = sort_entries(dirs_list)

            if use_detail:
                display_details(sortedList)
            else:
                display_default(sortedList)

if not use_brief:
    print("")
